json-iterator/go

README.md
any_test.go
feature_adapter.go
feature_any.go
feature_iter_object.go
feature_reflect.go
jsoniter.go
jsoniter_any_test.go
jsoniter_array_test.go
jsoniter_base64_test.go
jsoniter_customize_test.go
jsoniter_demo_test.go
jsoniter_find_end_test.go
jsoniter_float_test.go
jsoniter_int_test.go
jsoniter_io_test.go
jsoniter_large_file_test.go
jsoniter_map_test.go
jsoniter_nested_test.go
jsoniter_null_test.go
jsoniter_object_test.go
jsoniter_reflect_test.go
jsoniter_skip_test.go
jsoniter_string_test.go

根据 `gofmt` 和 `govet` 对源码进行修正，根据 `godoc` 对源码做了注释。  
已通过 `go test`。
目前 `goreport` 评分：
[![rcard](https://goreportcard.com/badge/github.com/hanbang-wang/go)](https://goreportcard.com/report/github.com/hanbang-wang/go)

Formated, doced. Also fixed few minor bugs.

---

example_test.go

As an example, I think jsoniter should be used instead json from standard lib.

Use jsoniter instead of json in example

---

feature_any_number.go
feature_any_string.go
feature_iter_int.go
jsoniter_any_bool_test.go
jsoniter_any_float_test.go
jsoniter_any_int_test.go

fix negative number to uint

---

feature_reflect_extension.go
jsoniter_object_test.go

Following [json-iterator/go#120](https://github.com/json-iterator/go/issues/120) , https://github.com/gin-gonic/gin/issues/991

fix(reflect): don't process ignored struct fields

---

feature_reflect.go

If the client is using the same jsoniter config with multiple goroutines
it's very likely that few initial operations will encounter a placeholder
encoder/decoder while the real one is being created by another
goroutine. Having a full second sleep seems too conservative, since
encoder/decoder will be created in a very short time. This is very easy
to reproduce in any real environment with a few concurrent requests of
the same type. A few initial requests will have 1s+ response time.
Changing to 10ms should smooth out marshal/unmarshal times for these
initial concurrent requests.

Shorter sleep while waiting for encoder/decoder

---

feature_reflect_native.go
jsoniter_bool_test.go
jsoniter_interface_test.go

Make sure we do the same thing as stdlib with null booleans by not
touching the original value and discarding the null.
Another somewhat related change is nulling out null interface values in
the original structure. This also matches stdlib behavior.

Allow null booleans

---

feature_reflect_native.go
jsoniter_interface_test.go

Before:
```
go test .
--- FAIL: Test_omitempty_nil_interface (0.00s)
Error Trace:    jsoniter_interface_test.go:371
Error:      	Not equal: 
expected: "{}"
actual: "{\"field\":null}"
FAIL
FAIL	github.com/json-iterator/go	0.148s
```
Relevant code in reflect package: https://golang.org/src/reflect/value.go#L132

Fix handling of nil empty interface

---

feature_reflect.go
feature_reflect_native.go
jsoniter_enum_marshaler_test.go

When MarshalJSON was defined on a pointer receiver custom enum type
marshaling/unmarshaling was panicing since the underlying primitive type
was treated as a pointer.
Since method set for pointer receivers includes value receiver methods
we don't really need optionalEncoder and can just use marshalEncoder
directly.
```
--- FAIL: Test_custom_marshaler_on_enum (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x133d7a6]
goroutine 6 [running]:
testing.tRunner.func1(0xc42007b1e0)
/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x13eb880, 0x1647d90)
/usr/local/go/src/runtime/panic.go:489 +0x2cf …
```

Fix custom marshaler for enum types

---

feature_reflect_native.go
jsoniter_bool_test.go
jsoniter_enum_marshaler_test.go
jsoniter_interface_test.go

This fixes a few more issues with encoding and decoding nil interfaces.
1. encoding nil non-empty interfaces was failing
2. encoding of nil `json.Marshaler` interfaces was failing
3. decoding of interfaces where the JSON value was nil was failing
Unrelated: replaced usage of `should.Equal(nil, err)` with `should.NoError(err)` in tests.

More nil interface fixes

---

feature_reflect_native.go
jsoniter_interface_test.go
jsoniter_null_test.go

1. Null values for primitive types no longer clear the original value in
the destination object.
2. Dereference multiple levels of pointers in the destination interface{}
type before unmarshaling into it. This is needed to match stdlib
behavior when working with nested interface{} fields. If the destination
object is a pointer to interface{} then the incoming nil value should
nil out the destination object but keep the reference to that nil value
on its parent object. However if the destination object is an
interface{} value it should set the reference to nil but keep the
original object intact.
3. Correctly handle typed nil decode destinations.

Improve stdlib compatibility

---

feature_reflect_extension.go
jsoniter_customize_test.go
jsoniter_struct_encoder_test.go

Skip creating encoders for unexported fields. They are not participating
in JSON marshaling anyway. This allows using unexported fields of
non-marshalable types in structs.
As a side-effect of this change it's no longer possible to marshal
unexported JSON fields by adding a custom type extenstion. It seems this
is desired behavior since it matches standard library and jsoniter
already disallows `json:"-"` fields from participating in custom
extensions.
Fixes #174.

Always skip unexported fields when encoding

---

compatible_test.go
feature_adapter.go
feature_config.go

Encode has trailing newline at the end.
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

Fix standard compatiblility

---

feature_config.go
feature_reflect_extension.go

目前是支持忽略tag为"-"的结构体项。
但有时结构体比较大，一个个去加会比较麻烦，不知道你们是否考虑接受增加这样一个选项。
这样生成的config就只处理带tag的项

加入一个OnlyTaggedField选项

---

feature_reflect_array.go
jsoniter_fixed_array_test.go

The array encoder assumed that arrays had at least one value, so it
would serialize them with a zero-value for the array, such as `[0]`.
This adds a test to reproduce the issue, and updates the encoder to
write an empty array if the length is 0.

Fix encoding 0-length arrays

---

feature_stream.go
feature_stream_float.go

The use of strconv.FormatFloat causes a string allocation,
by setting aside a reusable buffer and using strconv.AppendFloat
this can be avoided.
Before:
BenchmarkRespond-4           300           5392189 ns/op          618936 B/op      20010 allocs/op
After:
BenchmarkRespond-4           300           4713746 ns/op          139744 B/op         10 allocs/op
This benchmark is using a custom encoder that calls WriteFloat64 20k
times, which is the bulk of the work.

Remove allocs from WriteFloat32/WriteFloat64

---

reflect_struct_decoder.go
value_tests/error_test.go

Since the bot complained that #254 reduced coverage, I thought I would add some coverage of error conditions.
And I found that `generalStructDecoder` did not check for closing `}`.

Add a test for input errors, and fix one bug that it finds

---

pool.go

There is no need to keep reference to the writer - it is going to be overwritten on `BorrowStream()` anyway. This PR clears the reference to enable GC to collect the writer if it is no longer needed.

Release writer to enable GC

---

misc_tests/jsoniter_array_test.go
reflect_native.go

base64 decode fails if there is \n in byte slice
As mentioned in https://golang.org/pkg/encoding/base64/#Encoding.Decode
> New line characters (\r and \n) are ignored.
Therefore, I remove \r and \n before doing decode.

fix base64 contains newline case

---

Gopkg.lock
config.go
iter_object.go
reflect.go
reflect_struct_decoder.go

Fix https://github.com/kubernetes/kubernetes/issues/64612

Make case sensitivity optional

---

api_tests/config_test.go
reflect_struct_decoder.go

Fixes https://github.com/kubernetes/kubernetes/issues/64612#issuecomment-396097020
Follow-up for https://github.com/json-iterator/go/pull/282
Also see https://github.com/json-iterator/go/pull/282/files#r194283181

Fix case sensitivity

---

misc_tests/jsoniter_interface_test.go

Found using https://go-critic.github.io/overview#underef-ref

remove redundant dereferencing expressions

---

extra/binary_as_string_codec.go

Found using https://go-critic.github.io/overview#assignOp-ref

simplify `x = x <op> y` to `x <op>= y`

---

api_tests/marshal_json_test.go
reflect_marshaler.go

Fix the incompatible encoding #336 

---

misc_tests/jsoniter_array_test.go
reflect_native.go

Fixes https://github.com/json-iterator/go/issues/272
`[]byte` or `[]uint8` are encoded as base-64 encoded strings. So, only nil slices of these types should get marshalled as `null`, and non-nil empty slices should get marshalled as `""`.
This restores compatibility with the standard library.
I verified that this patch works locally. Even though tests for these exist in https://github.com/json-iterator/go/blob/master/type_tests/slice_test.go, I couldn't reproduce a case where the test case was fuzzed to an empty `[]byte` or `[]uint8` slice... :confused:
/cc @taowen @thockin 
fyi @liggitt @dims @neolit123

Don't marshal empty byte or uint8 slice as null

---

iter_skip.go
skip_tests/jsoniter_skip_test.go

This PR adds `AppendSkip` method that will allow buffer reuse between skips, as described in #372 
The following part was removed:
```go
if len(captured) == 0 {
copied := make([]byte, len(remaining))
copy(copied, remaining)
return copied
}
```
Because it is equivalent to `append(captured, remaining...)`.
Also I've removed the unused `captureBuffer` structure.
Please ping me if you need any adjustments, clarification or additional tests.

fix #372: add AppendSkip iterator method

---

misc_tests/jsoniter_map_test.go
reflect_map.go

Fixes #405 
- Add test to encode nil map and check for `null`
- Fix nil map being encoded as `{}`

Fixes #405 - Encode nil map into null

---

api_tests/marshal_json_escape_test.go
reflect_marshaler.go

use json.Marshaler again :-) then trim the last '\n' in reflect_marshaler.
fix #397

use json.Marshaler then trim the last '\n' in reflect_marshaler

---

iter.go
iter_array.go
iter_object.go
iter_skip_sloppy.go
misc_tests/jsoniter_nested_test.go
reflect.go
reflect_struct_decoder.go

This allows callers to limit input size to bound allocations / CPU, without needing to introspect the provided JSON to protect against internal decoder stack depth overflow.
See also https://tools.ietf.org/html/rfc7159#section-9 and golang issue 31789

Limit nesting depth

---

reflect_extension.go
type_tests/struct_embedded_test.go

solves: https://github.com/json-iterator/go/issues/415 
demo of bug: https://play.golang.org/p/QbqGl3ztXGs

Ignore unnamed literals in structs

---

api_tests/config_test.go
config.go
iter.go

Default `MaxDepth` is 10,000 to match the existing `maxDepth` constant added in #410
`ConfigCompatibleWithStandardLibrary` retains unlimited depth (via `-1`), until https://github.com/golang/go/issues/31789 has been decided (it got dropped from the 1.14 milestone)

Add MaxDepth as a config option

---

api_tests/config_test.go
config.go
iter.go

This reverts commit 44a7e7340d23d2e5d5d942966eb683436c027da0, reversing
changes made to dc11f49689fd1c9a6de20749def70bd889bf0d42.
This protects callers of the library by default. Given the golang parser is expected to set the same hard-coded limit in 1.15, I think more evidence is required before making this configurable and unsafe by default.
cc @taowen

Revert "Merge pull request #418 from bbrks/configurable_maxDepth"

---

reflect_map.go

Use one buffer for all encoded keys and values.
This significantly reduces allocations in my test of an array of 18 objects and each object has six fields.
```
benchmark                                old ns/op     new ns/op     delta
BenchmarkArrayJSONMarshal/jsoniter-8     67619         62885         -7.00%
benchmark                                old allocs     new allocs     delta
BenchmarkArrayJSONMarshal/jsoniter-8     500            393            -21.40%
benchmark                                old bytes     new bytes     delta
BenchmarkArrayJSONMarshal/jsoniter-8     30917         20421         -33.95%
```
It also brought allocations below the stdlib implementation for this test:
```
BenchmarkArrayJSONMarshal/stdlib-8         	   13418	     89073 ns/op	   26984 B/op	     466 …
```

Reduce allocations in sortKeysMapEncoder

---

extension_tests/decoder_test.go
reflect_map.go
reflect_struct_encoder.go

Hello, thank you for a library !
This pr fixes next problem:
1. We create jsoniter.Stream with SortMapKeys enable
2. Pass attachment to created stream
3. Try to serialize map with custom types
4. Attachment will be null on stream in Encode method
Example in test - *Test_custom_encoder_attachment*

fix nil attachment on stream in custom encoder on sorted map

---

reflect_map.go
value_tests/invalid_test.go

When invalid types inside a map were marshalled (in general, as soon as
sorted maps have been configured), the error message has not been
propagated out of the map's `subStream`.
Also fix and re-enable the channel test, which now resembles the
behavior of `encoding/json` and tests both default and compatible
configurations.
Signed-off-by: Jens Erat <email@jenserat.de>

pass nested error in compatible configuration, fixes #388

---

iter_object.go

In ReadObjectCb/ReadMapCb function, when the iterato read a token which is not '"' after '{', the error message should be ```expect " after {, but found xxx```, not ```expect " after }, but found xxx```

fix the error message typo of ReadObjectCB & ReadMapCb function

---

extra/naming_strategy.go
extra/naming_strategy_test.go

fix issue #326, the namingStrategyExtension should check if the field is private before updating the ```ToName``` and ```FromName``` array

fix issue #326

---

config.go
value_tests/raw_message_test.go

If the input json is integer/float, ```iter.Read()``` will meet EOF, which will make ```iter.Error``` not nil. But it's actually not an error.

fix issue #389 #411

---

any_str.go

Change-Id: Ic1690713d96940258811cdc149b1604128aa91a2

fix any str ToInt64 ToUint64 panic

---

misc_tests/jsoniter_object_test.go
reflect_struct_decoder.go

If a struct's type is anonymous, the decoder should not return an error message with its definition when it meets an error.

fix issue #421

---

benchmarks/stream_test.go
stream.go
stream_test.go

I believe that WriteMore should not call Flush for these reasons:
1. This is surprising for users because of inconsistency. Why call Flush in WriteMore and not in WriteObjectEnd?
2. It is not necessary; callers are free to call Flush if their use case demands it.
3. It harms performance in the common case by flushing the buffer much more frequently than it needs to be flushed.
The stream benchmark shows a 7% benefit to removing the Flush call, and I
observed a similar speedup in my real-world use case.
benchmark                                        old ns/op     new ns/op     delta
Benchmark_encode_string_with_SetEscapeHTML-8     442           437           -1.13%
Benchmark_jsoniter_large_file-8                  21222         21062         -0.75%
Benchmark_json_large_file-8 …

(*Stream).WriteMore: do not Flush

---

benchmarks/stream_test.go
stream.go
stream_test.go

Speeds up the example Stream usage in the benchmark by 20%

(*Stream).Flush: reuse buffer after successful flush

---

misc_tests/jsoniter_map_test.go
reflect_map.go
value_tests/map_test.go

This is to address the issue filed [here](https://github.com/json-iterator/go/issues/459).

Map keys of custom types should serialize using MarshalText when available

---

go.sum
reflect_struct_decoder.go
value_tests/struct_test.go

This fixes recently reported [bug](https://github.com/json-iterator/go/issues/478), when null is passed to number with json tag set to string. As highlighted in issue, standard library will place zero value in such case ([GoPlayground](https://play.golang.org/p/FyR6I63Ok0k)). However, `json-iterator` previously crashed with error like this:
```
--- FAIL: Test_unmarshal (0.00s)
--- FAIL: Test_unmarshal/[41]{"field":_null} (0.00s)
require.go:794: 
Error Trace:	value_test.go:52
Error:      	Received unexpected error:
Field: stringModeNumberDecoder: expect ", but found n, error found in #10 byte of ...|"field": null}|..., bigger context ...|{"field": null}|...
Test:       	Test_unmarshal/[41]{"field":_null}
Messages:   	jsoniter
```
Test plan:

fixed null in number json tag string

---

iter_int.go
misc_tests/jsoniter_int_test.go

This commit fixes bug in Iterator.assertInteger method if the next
conditions are met:
- Iterator reads data from `io.Reader`,
- expected value is `0` (zero)
- `Iterator.tail == Iterator.head + 1`
- `Iterator.tail < len(Iterator.buf)`
- value in the buffer after `Iterator.tail` is presented from the previous read and has '.' character.
Typical error which user cal see is:
- assertInteger: can not decode float as int, error found in #X byte of ...
Regression test added for checking the correct behaviour.
Fixes #476

jsoniter: Fix errors during reading integers from chunked io.Reader

---

iter_float.go
iter_int.go

fix issue 510

---

go.mod
go.sum

bumped stretchr to v1.8.0 as it depends on yaml v2 which has a critical vuln.

bumped stretchr to v1.8.0 to get rid of yaml v2 vuln

---

reflect_map.go
stream_float.go
value_tests/float_test.go

- https://github.com/golang/go/commit/ffbd31e9f79ad8b6aaeceac1397678e237581064
- https://github.com/golang/go/commit/92b3e3651dc44f54b458f171f641779f10fbaec0

encoding/json: Compatibility optimization
